@server=http://localhost:3000

### GET /api
GET {{server}}/api/

### GET /api/en
GET {{server}}/api/en

### GET /api/pt
GET {{server}}/api/pt

### GET /api/hello/en/:name (path parameter, route parameter)
GET {{server}}/api/hello/en/John

### GET /api/hello/en failure case (404 Not Found)
GET {{server}}/api/hello/en

### GET /api/hello/pt (query parameter, query string)
GET {{server}}/api/hello/pt?name=John

### GET /api/hello/pt failure case (400 Bad Request)
GET {{server}}/api/hello/pt

### POST /api/hello/es (body parameter, request body)
POST {{server}}/api/hello/es
Content-Type: application/json

{
  "name": "John"
}

### POST /api/hello/es failure case (400 Bad Request)
POST {{server}}/api/hello/es
Content-Type: application/json

{
  "person": "John"
}

### POST /api/hello/es failure case (400 Bad Request)
POST {{server}}/api/hello/es
