FROM node:22-alpine

WORKDIR /app
ENV DATABASE_URL=file:./src/database/db.dev.sqlite

COPY package*.json ./
COPY prisma/ ./prisma/
COPY prisma.config.ts ./
RUN npm ci

COPY tsconfig.json ./
COPY src/ ./src/
COPY public/ ./public

EXPOSE 3000

CMD ["sh", "-c", "npm run db:generate && npm run dev"]
