FROM node:24-alpine

WORKDIR /app

COPY package*.json ./
COPY prisma/ ./prisma/
COPY prisma.config.ts ./
RUN npm ci

COPY tsconfig.json ./
COPY src/ ./src/
COPY public/ ./public

EXPOSE 3000

CMD ["sh", "-c", "npx prisma migrate deploy && npm run db:generate && npm run dev"]
